### ISSUE TITLE
account data not refreshing

### ISSUE THREAD

**Issue by DenymW** [robcarver17/ibswigsystematicexamples#3]
good day,

I have been following your guides and have built up a trial trader, however I am having trouble with getting updated account details. Specifically the system is able to get the cash balance on the account on start up and make the same call every cycle to update the current account balance, however when it makes those subsequent calls it returns the initial cash value amount and not the updated values.

any help would be greatly appreciated.

kind regards,
Denym

**Comment by robcarver17** [comment]
Is this the demo account, or a real account?

**Comment by DenymW** [comment]
demo account

**Comment by robcarver17** [comment]
This is a known feature of the demo account, there is nothing you can do about it. You need to open a paper trading account to get realistic balances.

**Comment by DenymW** [comment]
just so you know when using ezibpy it is able to get refreshed account data while using the demo account, to enact papertrading on the demo account I have used an implementation of swigibpy based off your fantastic tutorials and get the current account details using an implementation of ezibpy.
